### ISSUE TITLE
tbb_example.c not tested?

### ISSUE THREAD

**Issue by epruesse** [conda-forge/tbb-feedstock#33]
I presume the file `tbb_example.c` in the `recipe` folder was meant as a test case? I don't see it actually getting compiled (and run), though.

**Comment by anton-malakhov** [comment]
right, it is kind of leftover from the previous recipe structure which become useless as soon as tbb4py python module was added, it serves as both compilation test and simple library test. Though, I'm inclining to include full-fledged unit testing of the library into this recipe one day

**Comment by anton-malakhov** [comment]
I have removed the `tbb_example.c` from the  recipe and used TBB's example for sake of testing instead. Closing, thanks!
