### ISSUE TITLE
tbb-devel ?

### ISSUE THREAD

**Issue by jschueller** [conda-forge/tbb-feedstock#64]
I think its unecessary to provide a devel subpackage because libraries with public dependencies on tbb headers have to add tbb-devel to the runtime section: (https://github.com/conda-forge/vtk-feedstock/issues/134, openturns-feedstock), also its quite unusual in conda (it's not like debian or rpms)
what's the motive of such a package ? why not put everything in tbb (except the python part of course)

Also why provide the doc ? conda packages usually strip off the doc

**Comment by anton-malakhov** [comment]
there are multiple reasons to keep tbb-devel:
* size of the package - people are happy when it's not as big
* delivering debug and preview versions of TBB libraries
* where to install other files like licenses, notes, docs and examples? We are doing full release as in official bundles
* converge different vendors of TBB packages on this layout

**Comment by jschueller** [comment]
I'm still not convinced :)
