### ISSUE TITLE
Question: how to introduce new major version with incompatibilities with previous?

### ISSUE THREAD

**Issue by AlexVeprev** [conda-forge/tbb-feedstock#75]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

**Question**: current development version of [oneTBB](https://github.com/oneapi-src/oneTBB) (future 2021) has incompatibilities with the current released one (TBB 2020), so there is a risk that packages depending on TBB may become broken in case of update. Is it acceptable in case of major version change? If not how to perform the update?

@isuruf, @beckermr, what do you think?

FYI: @napetrov @alexey-katranov

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by beckermr** [comment]
Which packages are incompatible between the versions? Just tbb-devel, or more of them?

We could use a repodata patch to set an upper bound for any package that depends on tbb and introduce an upper bound in the feedstock as well.

**Comment by AlexVeprev** [comment]
> Which packages are incompatible between the versions? Just tbb-devel, or more of them?

`tbb` package too, some binaries will have updated versioning, for example:

- `libtbb.so.2` is replaced with `libtbb.so.12 -> libtbb.so.12.1`
- `tbb.dll` is replaced with `tbb12.dll`
- similar update for macOS.

Not sure about `tbb4py` for now.

>We could use a repodata patch

I'm not so familiar with conda/conda-forge yet, could you please clarify: should it be done separately in each package that depends on TBB or can be done just from tbb-feedstock side or in some other centralized place?

**Comment by beckermr** [comment]
OK. Bumping @conda-forge/core for guidance. 

The repodata patches are here: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock. We use them to change the metadata of existing packages in cases like this. So for example, we could add a patch that finds every package that depends on tbb and puts in a constraint tbb < 2021 to ensure compatibility. 

We should also be adjusting the feedstock here to ensure that we have the proper run exports in the places they are needed.

**Comment by ocefpaf** [comment]
@beckermr that is pretty much it. When a repodata patch is too hard we accepted marking the package as broken and producing a new one with a higher build number.

**Comment by AlexVeprev** [comment]
@beckermr, @ocefpaf, thank you! Now I know that it is possible, specific technical details may be discussed in a PR for the new version.
